/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;

/**
 *
 * @author camin
 */
public class Acceuil_Sec extends javax.swing.JFrame {

    /**
     * Creates new form Acceuille_Radiologue
     */
    public Acceuil_Sec() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Base = new javax.swing.JPanel();
        Jpanel_Head = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTabbedPane_Corps = new javax.swing.JTabbedPane();
        jPanel_Corps_Exam = new javax.swing.JPanel();
        jScrollPane_Corps_Exam_Tab = new javax.swing.JScrollPane();
        jTable_Exam = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane_Corps_Exam_Tab2 = new javax.swing.JScrollPane();
        jTable_Exam2 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel_RechercheParDMR1 = new javax.swing.JLabel();
        jComboBox_RechercheDMR1 = new javax.swing.JComboBox<>();
        jTextField_RechercheDMR1 = new javax.swing.JTextField();
        jButton_RechercherDMR1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton_OuvrirDMR1 = new javax.swing.JButton();
        jButton_OuvrirDMR2 = new javax.swing.JButton();
        jPanel_DMR = new javax.swing.JPanel();
        jLabel_RechercheParDMR = new javax.swing.JLabel();
        jTextField_RechercheDMR = new javax.swing.JTextField();
        jButton_RechercherDMR = new javax.swing.JButton();
        jComboBox_RechercheDMR = new javax.swing.JComboBox<>();
        jButton_CreerDMR = new javax.swing.JButton();
        jButton_ImprimerDMR = new javax.swing.JButton();
        jScrollPane_Corps_DMR = new javax.swing.JScrollPane();
        jTable_DMR = new javax.swing.JTable();
        jLabel_NbResult = new javax.swing.JLabel();
        jLabel_NbResultDMR = new javax.swing.JLabel();
        jPanel_ApercuDMR = new javax.swing.JPanel();
        jScrollPane_ApercuDMR = new javax.swing.JScrollPane();
        jTextArea_ApercuDMR = new javax.swing.JTextArea();
        jButton_OuvrirDMR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Accueil");
        setResizable(false);

        jPanel_Base.setBackground(new java.awt.Color(127, 144, 160));
        jPanel_Base.setPreferredSize(new java.awt.Dimension(1089, 700));
        jPanel_Base.setLayout(new java.awt.BorderLayout());

        Jpanel_Head.setBackground(new java.awt.Color(127, 144, 160));
        Jpanel_Head.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Jpanel_Head.setPreferredSize(new java.awt.Dimension(1089, 115));

        jLabel4.setText("Radiologue");

        jLabel3.setText("Lary");

        jLabel2.setText("BAMBEL");

        jButton1.setText("Déconnexion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Parametres");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout Jpanel_HeadLayout = new javax.swing.GroupLayout(Jpanel_Head);
        Jpanel_Head.setLayout(Jpanel_HeadLayout);
        Jpanel_HeadLayout.setHorizontalGroup(
            Jpanel_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_HeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 487, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        Jpanel_HeadLayout.setVerticalGroup(
            Jpanel_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_HeadLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(Jpanel_HeadLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel_Base.add(Jpanel_Head, java.awt.BorderLayout.NORTH);
        Jpanel_Head.getAccessibleContext().setAccessibleName("Head_Panel");

        jTabbedPane_Corps.setBackground(new java.awt.Color(127, 144, 160));
        jTabbedPane_Corps.setToolTipText("");
        jTabbedPane_Corps.setPreferredSize(new java.awt.Dimension(1089, 585));
        jTabbedPane_Corps.setVerifyInputWhenFocusTarget(false);

        jPanel_Corps_Exam.setBackground(new java.awt.Color(163, 209, 180));
        jPanel_Corps_Exam.setPreferredSize(new java.awt.Dimension(1089, 585));

        jScrollPane_Corps_Exam_Tab.setToolTipText("");

        jTable_Exam.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTable_Exam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Heure", "Nom", "Exam", "Urgent"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Exam.setToolTipText("");
        Font f = new Font("Dialog", Font.PLAIN, 18);
        JTableHeader header = jTable_Exam.getTableHeader();
        header.setFont(f);
        jTable_Exam.getTableHeader().setReorderingAllowed(false);
        jTable_Exam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ExamMouseClicked(evt);
            }
        });
        jScrollPane_Corps_Exam_Tab.setViewportView(jTable_Exam);
        if (jTable_Exam.getColumnModel().getColumnCount() > 0) {
            jTable_Exam.getColumnModel().getColumn(0).setResizable(false);
            jTable_Exam.getColumnModel().getColumn(1).setResizable(false);
            jTable_Exam.getColumnModel().getColumn(2).setResizable(false);
            jTable_Exam.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel7.setText("Demande de rendez vous en attente :");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel5.setText("Nb_RDV");

        jScrollPane_Corps_Exam_Tab2.setToolTipText("");
        jScrollPane_Corps_Exam_Tab2.setPreferredSize(new java.awt.Dimension(453, 369));

        jTable_Exam2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTable_Exam2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"08:00", "DUPOND", "Scanner Cervicale ", "Terminé"},
                {"08:30", "DUPONT", "Scanner Main", "Terminé"},
                {"09:00", "DUPON", "Scanner Rocher", "En cours"},
                {"09:30", "DHUPOND", "Scanner", null},
                {"10:00", "DHUPONT", "Scanner", null},
                {"10:30", "DHUPON", "Scanner", null},
                {"11:00", "DUHPOND", "Scanner", null},
                {"11:30", "DUHPONT", "Scanner", null},
                {"12:00", "DUHPON", "Scanner", null},
                {"12:30", "DHUHPOND", "Scanner", null},
                {"13:00", "DHUHPONT", "Scanner", null},
                {"13:30", "DHUHPON", "Scanner", null},
                {"14:00", "DUUPOND", "Scanner", null},
                {"14:30", "DUUPONT", "Scanner", null},
                {"15:00", "DUUPON", "Scanner", null},
                {"15:30", null, null, null},
                {"16:00", null, null, null},
                {"16:30", null, null, null},
                {"17:00", null, null, null},
                {"17:30", null, null, null},
                {"18:00", null, null, null},
                {"18:30", null, null, null}
            },
            new String [] {
                "Heure", "Nom", "Exam", "Etat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Exam2.setToolTipText("");
        Font fbis = new Font("Dialog", Font.PLAIN, 18);
        JTableHeader headerbis = jTable_Exam2.getTableHeader();
        headerbis.setFont(fbis);
        jTable_Exam2.setPreferredSize(new java.awt.Dimension(300, 369));
        jTable_Exam2.getTableHeader().setReorderingAllowed(false);
        jTable_Exam2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Exam2MouseClicked(evt);
            }
        });
        jScrollPane_Corps_Exam_Tab2.setViewportView(jTable_Exam2);

        jComboBox1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salle 1", "Salle 2" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel_RechercheParDMR1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel_RechercheParDMR1.setText("Recherche par :");

        jComboBox_RechercheDMR1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jComboBox_RechercheDMR1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nom" }));
        jComboBox_RechercheDMR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_RechercheDMR1ActionPerformed(evt);
            }
        });

        jTextField_RechercheDMR1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTextField_RechercheDMR1.setText("Recherche à effectuer");
        jTextField_RechercheDMR1.setToolTipText("");
        jTextField_RechercheDMR1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_RechercheDMR1FocusGained(evt);
            }
        });
        jTextField_RechercheDMR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_RechercheDMR1ActionPerformed(evt);
            }
        });

        jButton_RechercherDMR1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jButton_RechercherDMR1.setText("Rerchercher");

        jComboBox2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "date j", "date j+1", "date j+2", "date j+3" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton_OuvrirDMR1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jButton_OuvrirDMR1.setText("Ouvrir");
        jButton_OuvrirDMR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OuvrirDMR1ActionPerformed(evt);
            }
        });

        jButton_OuvrirDMR2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jButton_OuvrirDMR2.setText("Valider");
        jButton_OuvrirDMR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OuvrirDMR2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Corps_ExamLayout = new javax.swing.GroupLayout(jPanel_Corps_Exam);
        jPanel_Corps_Exam.setLayout(jPanel_Corps_ExamLayout);
        jPanel_Corps_ExamLayout.setHorizontalGroup(
            jPanel_Corps_ExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Corps_ExamLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_Corps_ExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_Corps_ExamLayout.createSequentialGroup()
                        .addComponent(jButton_OuvrirDMR2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_OuvrirDMR1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_Corps_ExamLayout.createSequentialGroup()
                        .addGroup(jPanel_Corps_ExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_Corps_ExamLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5))
                            .addComponent(jScrollPane_Corps_Exam_Tab, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                        .addGroup(jPanel_Corps_ExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_Corps_ExamLayout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_Corps_ExamLayout.createSequentialGroup()
                                .addComponent(jLabel_RechercheParDMR1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_RechercheDMR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jTextField_RechercheDMR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jButton_RechercherDMR1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane_Corps_Exam_Tab2, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        jPanel_Corps_ExamLayout.setVerticalGroup(
            jPanel_Corps_ExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Corps_ExamLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_Corps_ExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_RechercheDMR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_RechercheParDMR1)
                    .addComponent(jTextField_RechercheDMR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_RechercherDMR1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addGap(11, 11, 11)
                .addGroup(jPanel_Corps_ExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel_Corps_ExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane_Corps_Exam_Tab, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane_Corps_Exam_Tab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(jPanel_Corps_ExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_OuvrirDMR1)
                    .addComponent(jButton_OuvrirDMR2))
                .addGap(23, 23, 23))
        );

        jTabbedPane_Corps.addTab("Planning", jPanel_Corps_Exam);

        jPanel_DMR.setBackground(new java.awt.Color(163, 209, 180));
        jPanel_DMR.setPreferredSize(new java.awt.Dimension(1089, 585));

        jLabel_RechercheParDMR.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel_RechercheParDMR.setText("Recherche par :");

        jTextField_RechercheDMR.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTextField_RechercheDMR.setText("Recherche à effectuer");
        jTextField_RechercheDMR.setToolTipText("");
        jTextField_RechercheDMR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_RechercheDMRFocusGained(evt);
            }
        });
        jTextField_RechercheDMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_RechercheDMRActionPerformed(evt);
            }
        });

        jButton_RechercherDMR.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jButton_RechercherDMR.setText("Rerchercher");

        jComboBox_RechercheDMR.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jComboBox_RechercheDMR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nom" }));
        jComboBox_RechercheDMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_RechercheDMRActionPerformed(evt);
            }
        });

        jButton_CreerDMR.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jButton_CreerDMR.setText("Créer DMR");

        jButton_ImprimerDMR.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jButton_ImprimerDMR.setText("Imprimer apercu");

        jScrollPane_Corps_DMR.setToolTipText("");

        jTable_DMR.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTable_DMR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "ID", "Nom", "Nombre Exam"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_DMR.setToolTipText("");
        JTableHeader headerbibis = jTable_DMR.getTableHeader();
        headerbibis.setFont(fbis);
        jTable_DMR.getTableHeader().setReorderingAllowed(false);
        jTable_DMR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DMRMouseClicked(evt);
            }
        });
        jScrollPane_Corps_DMR.setViewportView(jTable_DMR);

        jLabel_NbResult.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel_NbResult.setText("Nombre de résultat :");

        jLabel_NbResultDMR.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel_NbResultDMR.setText("Nb_resultat");

        jPanel_ApercuDMR.setBackground(new java.awt.Color(163, 209, 180));
        jPanel_ApercuDMR.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Exam", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24))); // NOI18N

        jTextArea_ApercuDMR.setColumns(20);
        jTextArea_ApercuDMR.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTextArea_ApercuDMR.setRows(5);
        jTextArea_ApercuDMR.setText(">> Apercu\n\nNOM : DUPOND\nPRENOM : AAAAAA\n\n/*\n\nExam 1\nExam 2\nExam 3\n\n\n\n*/");
        jScrollPane_ApercuDMR.setViewportView(jTextArea_ApercuDMR);

        javax.swing.GroupLayout jPanel_ApercuDMRLayout = new javax.swing.GroupLayout(jPanel_ApercuDMR);
        jPanel_ApercuDMR.setLayout(jPanel_ApercuDMRLayout);
        jPanel_ApercuDMRLayout.setHorizontalGroup(
            jPanel_ApercuDMRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane_ApercuDMR, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        jPanel_ApercuDMRLayout.setVerticalGroup(
            jPanel_ApercuDMRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane_ApercuDMR, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );

        jButton_OuvrirDMR.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jButton_OuvrirDMR.setText("Ouvrir");
        jButton_OuvrirDMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OuvrirDMRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_DMRLayout = new javax.swing.GroupLayout(jPanel_DMR);
        jPanel_DMR.setLayout(jPanel_DMRLayout);
        jPanel_DMRLayout.setHorizontalGroup(
            jPanel_DMRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_DMRLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_DMRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_DMRLayout.createSequentialGroup()
                        .addComponent(jLabel_RechercheParDMR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_RechercheDMR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jTextField_RechercheDMR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton_RechercherDMR, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_DMRLayout.createSequentialGroup()
                        .addComponent(jLabel_NbResult)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_NbResultDMR))
                    .addComponent(jButton_OuvrirDMR, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane_Corps_DMR))
                .addGap(88, 88, 88)
                .addGroup(jPanel_DMRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_ApercuDMR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_DMRLayout.createSequentialGroup()
                        .addComponent(jButton_CreerDMR, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_ImprimerDMR, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel_DMRLayout.setVerticalGroup(
            jPanel_DMRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DMRLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_DMRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_DMRLayout.createSequentialGroup()
                        .addGroup(jPanel_DMRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_RechercheDMR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_RechercheParDMR)
                            .addComponent(jTextField_RechercheDMR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_RechercherDMR))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel_DMRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_NbResult)
                            .addComponent(jLabel_NbResultDMR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane_Corps_DMR, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel_ApercuDMR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel_DMRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_DMRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_CreerDMR)
                        .addComponent(jButton_ImprimerDMR))
                    .addComponent(jButton_OuvrirDMR))
                .addGap(20, 20, 20))
        );

        jTabbedPane_Corps.addTab("DMR", jPanel_DMR);

        jPanel_Base.add(jTabbedPane_Corps, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel_Base, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int retour = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment vous déconnecter ?", "Attention", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (retour == JOptionPane.OK_OPTION) {
            this.dispose(); // ferme la fenetre

            // new Login().setVisible(true); // ouvre la fenetre de connection
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable_ExamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ExamMouseClicked
        // TODO add your handling code here:
        //condition si l'exam n'existe pas déjà (cf dernière colonne)
        if (evt.getClickCount() == 2) {

            if (jTable_Exam.getSelectedRowCount() > 0) {

                int retour = JOptionPane.showConfirmDialog(this, "L'examen n'existe pas encore, souhaitez vous le créer ?", "Information", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if (retour == JOptionPane.OK_OPTION) {
                    // ouvre la page de création et modifie valeur de la dernière colonne
                }
            }
        }
    }//GEN-LAST:event_jTable_ExamMouseClicked

    private void jTable_Exam2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Exam2MouseClicked
        // TODO add your handling code here:
        //condition si l'exam n'existe pas déjà (cf dernière colonne)
        if (evt.getClickCount() == 2) {

            if (jTable_Exam.getSelectedRowCount() > 0) {

                int retour = JOptionPane.showConfirmDialog(this, "L'examen n'existe pas encore, souhaitez vous le créer ?", "Information", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if (retour == JOptionPane.OK_OPTION) {
                    // ouvre la page de création et modifie valeur de la dernière colonne
                }
            }
        }
    }//GEN-LAST:event_jTable_Exam2MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox_RechercheDMR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_RechercheDMR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_RechercheDMR1ActionPerformed

    private void jTextField_RechercheDMR1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_RechercheDMR1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_RechercheDMR1FocusGained

    private void jTextField_RechercheDMR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_RechercheDMR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_RechercheDMR1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton_OuvrirDMR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OuvrirDMR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_OuvrirDMR1ActionPerformed

    private void jButton_OuvrirDMR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OuvrirDMR2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_OuvrirDMR2ActionPerformed

    private void jTextField_RechercheDMRFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_RechercheDMRFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_RechercheDMRFocusGained

    private void jTextField_RechercheDMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_RechercheDMRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_RechercheDMRActionPerformed

    private void jComboBox_RechercheDMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_RechercheDMRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_RechercheDMRActionPerformed

    private void jTable_DMRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DMRMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_DMRMouseClicked

    private void jButton_OuvrirDMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OuvrirDMRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_OuvrirDMRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceuil_Sec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceuil_Sec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceuil_Sec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceuil_Sec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceuil_Sec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanel_Head;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_CreerDMR;
    private javax.swing.JButton jButton_ImprimerDMR;
    private javax.swing.JButton jButton_OuvrirDMR;
    private javax.swing.JButton jButton_OuvrirDMR1;
    private javax.swing.JButton jButton_OuvrirDMR2;
    private javax.swing.JButton jButton_RechercherDMR;
    private javax.swing.JButton jButton_RechercherDMR1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox_RechercheDMR;
    private javax.swing.JComboBox<String> jComboBox_RechercheDMR1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_NbResult;
    private javax.swing.JLabel jLabel_NbResultDMR;
    private javax.swing.JLabel jLabel_RechercheParDMR;
    private javax.swing.JLabel jLabel_RechercheParDMR1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_ApercuDMR;
    private javax.swing.JPanel jPanel_Base;
    private javax.swing.JPanel jPanel_Corps_Exam;
    private javax.swing.JPanel jPanel_DMR;
    private javax.swing.JScrollPane jScrollPane_ApercuDMR;
    private javax.swing.JScrollPane jScrollPane_Corps_DMR;
    private javax.swing.JScrollPane jScrollPane_Corps_Exam_Tab;
    private javax.swing.JScrollPane jScrollPane_Corps_Exam_Tab2;
    private javax.swing.JTabbedPane jTabbedPane_Corps;
    private javax.swing.JTable jTable_DMR;
    private javax.swing.JTable jTable_Exam;
    private javax.swing.JTable jTable_Exam2;
    private javax.swing.JTextArea jTextArea_ApercuDMR;
    private javax.swing.JTextField jTextField_RechercheDMR;
    private javax.swing.JTextField jTextField_RechercheDMR1;
    // End of variables declaration//GEN-END:variables
}
