/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author camin
 */
public class Acceuille_Radiologue extends javax.swing.JFrame {

    /**
     * Creates new form Acceuille_Radiologue
     */
    public Acceuille_Radiologue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpanel_Head = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTabbedPane_Corps = new javax.swing.JTabbedPane();
        jPanel_Corps_Exam = new javax.swing.JPanel();
        jPanel_Corps_Exam_Recherche = new javax.swing.JPanel();
        jTextField_Recherche = new javax.swing.JTextField();
        jLabel_RecherchePar = new javax.swing.JLabel();
        jRadioButton_Nom = new javax.swing.JRadioButton();
        jRadioButton_Exam = new javax.swing.JRadioButton();
        jRadioButton_Id = new javax.swing.JRadioButton();
        jButton_Rechercher = new javax.swing.JButton();
        jScrollPane_Corps_Exam_Tab = new javax.swing.JScrollPane();
        jTable_Exam = new javax.swing.JTable();
        jPanel_Apercu = new javax.swing.JPanel();
        jButton_AddRapport = new javax.swing.JButton();
        jButton_Ouvrir = new javax.swing.JButton();
        jButton_Imprimer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 700));
        setResizable(false);

        Jpanel_Head.setBackground(new java.awt.Color(204, 204, 255));
        Jpanel_Head.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("jLabel1");

        jLabel2.setText("Nom");

        jLabel3.setText("Prenom");

        jLabel4.setText("Poste");

        jButton1.setText("Déconnexion");

        jButton2.setText("Parametres");

        javax.swing.GroupLayout Jpanel_HeadLayout = new javax.swing.GroupLayout(Jpanel_Head);
        Jpanel_Head.setLayout(Jpanel_HeadLayout);
        Jpanel_HeadLayout.setHorizontalGroup(
            Jpanel_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_HeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Jpanel_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel_HeadLayout.createSequentialGroup()
                        .addGroup(Jpanel_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_HeadLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 637, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        Jpanel_HeadLayout.setVerticalGroup(
            Jpanel_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_HeadLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_HeadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Jpanel_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Jpanel_HeadLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(Jpanel_Head, java.awt.BorderLayout.NORTH);
        Jpanel_Head.getAccessibleContext().setAccessibleName("Head_Panel");

        jTabbedPane_Corps.setBackground(new java.awt.Color(153, 153, 255));

        jPanel_Corps_Exam.setBackground(new java.awt.Color(153, 153, 255));

        jTextField_Recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_RechercheActionPerformed(evt);
            }
        });

        jLabel_RecherchePar.setText("Recherche par :");

        jRadioButton_Nom.setText("Nom");
        jRadioButton_Nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_NomActionPerformed(evt);
            }
        });

        jRadioButton_Exam.setText("Exam");

        jRadioButton_Id.setText("ID");
        jRadioButton_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_IdActionPerformed(evt);
            }
        });

        jButton_Rechercher.setText("Rerchercher");

        javax.swing.GroupLayout jPanel_Corps_Exam_RechercheLayout = new javax.swing.GroupLayout(jPanel_Corps_Exam_Recherche);
        jPanel_Corps_Exam_Recherche.setLayout(jPanel_Corps_Exam_RechercheLayout);
        jPanel_Corps_Exam_RechercheLayout.setHorizontalGroup(
            jPanel_Corps_Exam_RechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Corps_Exam_RechercheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Corps_Exam_RechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_Recherche)
                    .addComponent(jLabel_RecherchePar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Rechercher, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_Corps_Exam_RechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton_Id)
                    .addComponent(jRadioButton_Nom)
                    .addComponent(jRadioButton_Exam))
                .addGap(20, 20, 20))
        );
        jPanel_Corps_Exam_RechercheLayout.setVerticalGroup(
            jPanel_Corps_Exam_RechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Corps_Exam_RechercheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Corps_Exam_RechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Corps_Exam_RechercheLayout.createSequentialGroup()
                        .addComponent(jRadioButton_Id)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_Nom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_Exam))
                    .addGroup(jPanel_Corps_Exam_RechercheLayout.createSequentialGroup()
                        .addComponent(jLabel_RecherchePar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_Recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Rechercher)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable_Exam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "ID", "Nom", "Exam", "Rapport"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Exam.setToolTipText("");
        jScrollPane_Corps_Exam_Tab.setViewportView(jTable_Exam);
        if (jTable_Exam.getColumnModel().getColumnCount() > 0) {
            jTable_Exam.getColumnModel().getColumn(0).setResizable(false);
            jTable_Exam.getColumnModel().getColumn(1).setResizable(false);
            jTable_Exam.getColumnModel().getColumn(2).setResizable(false);
            jTable_Exam.getColumnModel().getColumn(3).setResizable(false);
            jTable_Exam.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel_ApercuLayout = new javax.swing.GroupLayout(jPanel_Apercu);
        jPanel_Apercu.setLayout(jPanel_ApercuLayout);
        jPanel_ApercuLayout.setHorizontalGroup(
            jPanel_ApercuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel_ApercuLayout.setVerticalGroup(
            jPanel_ApercuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton_AddRapport.setText("Ajouter Rapport");

        jButton_Ouvrir.setText("Ouvrir");

        jButton_Imprimer.setText("Imprimer");

        javax.swing.GroupLayout jPanel_Corps_ExamLayout = new javax.swing.GroupLayout(jPanel_Corps_Exam);
        jPanel_Corps_Exam.setLayout(jPanel_Corps_ExamLayout);
        jPanel_Corps_ExamLayout.setHorizontalGroup(
            jPanel_Corps_ExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Corps_ExamLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_Corps_ExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Corps_ExamLayout.createSequentialGroup()
                        .addComponent(jButton_AddRapport, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Ouvrir, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_Corps_ExamLayout.createSequentialGroup()
                        .addGroup(jPanel_Corps_ExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane_Corps_Exam_Tab, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel_Corps_Exam_Recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel_Apercu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel_Corps_ExamLayout.setVerticalGroup(
            jPanel_Corps_ExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Corps_ExamLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_Corps_ExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_Corps_ExamLayout.createSequentialGroup()
                        .addComponent(jPanel_Corps_Exam_Recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane_Corps_Exam_Tab, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel_Apercu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Corps_ExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Corps_ExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Ouvrir)
                        .addComponent(jButton_Imprimer))
                    .addComponent(jButton_AddRapport))
                .addGap(20, 20, 20))
        );

        jTabbedPane_Corps.addTab("Exam", jPanel_Corps_Exam);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1041, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        jTabbedPane_Corps.addTab("Patient (Idem que l'autre page mais affiche une ligne = un patient, on voit tout les exams du patients dans l'apercu ", jPanel2);

        getContentPane().add(jTabbedPane_Corps, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_RechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_RechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_RechercheActionPerformed

    private void jRadioButton_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_IdActionPerformed

    private void jRadioButton_NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_NomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_NomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceuille_Radiologue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceuille_Radiologue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceuille_Radiologue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceuille_Radiologue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceuille_Radiologue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanel_Head;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_AddRapport;
    private javax.swing.JButton jButton_Imprimer;
    private javax.swing.JButton jButton_Ouvrir;
    private javax.swing.JButton jButton_Rechercher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_RecherchePar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_Apercu;
    private javax.swing.JPanel jPanel_Corps_Exam;
    private javax.swing.JPanel jPanel_Corps_Exam_Recherche;
    private javax.swing.JRadioButton jRadioButton_Exam;
    private javax.swing.JRadioButton jRadioButton_Id;
    private javax.swing.JRadioButton jRadioButton_Nom;
    private javax.swing.JScrollPane jScrollPane_Corps_Exam_Tab;
    private javax.swing.JTabbedPane jTabbedPane_Corps;
    private javax.swing.JTable jTable_Exam;
    private javax.swing.JTextField jTextField_Recherche;
    // End of variables declaration//GEN-END:variables
}
