/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import BD.Gestion_examen;
import BD.Gestion_patient;
import NF.*;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.time.LocalDate;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author camin
 */
public class Crea_Rapport extends javax.swing.JFrame {

    private Patient patient_courant;
    private Examen examen_courant;
    private Connection connexion;

    //Code utile
//        private Patient patient_courant ;
//    private Examen examen_courant ;
    private Salle salle_courante;
    private PACS pacs_courant;
    private BufferedImage image_courante;
    PanelImageRapport panel_image;

    /**
     * Creates new form Acceuille_Radiologue
     */
    public Crea_Rapport() {
        initComponents();
    }

    public Crea_Rapport(Patient patient_courant, Examen examen_courant, ObjetCourant objet_Courant) {
        this.patient_courant = patient_courant;
        System.out.println(examen_courant);
        this.examen_courant = examen_courant;
        this.connexion = objet_Courant.getConnexion();
        salle_courante = Gestion_examen.recuperer_salle(String.valueOf(examen_courant.getId_examen()), connexion);
        pacs_courant = Gestion_examen.recuperer_pacs(String.valueOf(examen_courant.getId_examen()), connexion);
        image_courante = Gestion_examen.recuperer_image(String.valueOf(examen_courant.getId_examen()), connexion);
        panel_image = new PanelImageRapport(image_courante);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        datelabel = new javax.swing.JLabel();
        JPanel_Base = new javax.swing.JPanel();
        Jpanel_Head = new javax.swing.JPanel();
        jLabel_Logo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel_Corps = new javax.swing.JPanel();
        jPanel_InfoPatient = new javax.swing.JPanel();
        jLabel_ID = new javax.swing.JLabel();
        jLabel_Nom = new javax.swing.JLabel();
        jLabel_Prenom = new javax.swing.JLabel();
        jLabel_DDN = new javax.swing.JLabel();
        jLabel_Sexe = new javax.swing.JLabel();
        jLabel_Age = new javax.swing.JLabel();
        jLabel_Adresse = new javax.swing.JLabel();
        idPatient = new javax.swing.JLabel();
        nomPatient = new javax.swing.JLabel();
        prenomPatient = new javax.swing.JLabel();
        dateNaissancePatient = new javax.swing.JLabel();
        sexePatient = new javax.swing.JLabel();
        agePatient = new javax.swing.JLabel();
        adressePatient = new javax.swing.JLabel();
        jPanel_InfoActe = new javax.swing.JPanel();
        jLabel_TypeExam = new javax.swing.JLabel();
        jLabel_Nompract = new javax.swing.JLabel();
        jLabel_Prenompract = new javax.swing.JLabel();
        jLabel_IDpract = new javax.swing.JLabel();
        typeExamen = new javax.swing.JLabel();
        nomPraticien = new javax.swing.JLabel();
        prenomPraticien = new javax.swing.JLabel();
        idPraticien = new javax.swing.JLabel();
        datexam = new javax.swing.JLabel();
        jLabel_LinkWord = new javax.swing.JLabel();
        heurexam = new javax.swing.JLabel();
        jLabel_IDexam = new javax.swing.JLabel();
        idexamen = new javax.swing.JLabel();
        jSeparator = new javax.swing.JSeparator();
        jLabel_Indication = new javax.swing.JLabel();
        jScrollPane_Indication = new javax.swing.JScrollPane();
        jTextPane_Indication = new javax.swing.JTextPane();
        jLabel_Technique = new javax.swing.JLabel();
        jScrollPane_Technique = new javax.swing.JScrollPane();
        jTextPane_Technique = new javax.swing.JTextPane();
        jPanel_Image = new javax.swing.JPanel();
        jComboBox_Image = new javax.swing.JComboBox<>();
        imageRadio = new PanelImageRapport(image_courante);
        jScrollPane_CR = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel_AddRapport = new javax.swing.JLabel();
        jButton_Sauvegarder = new javax.swing.JButton();
        jSlider_Luminosite = new javax.swing.JSlider();
        jButton_RotD = new javax.swing.JButton();
        jLabel_Luminosite = new javax.swing.JLabel();
        jLabel_Contraste = new javax.swing.JLabel();
        jButton_Imprimer = new javax.swing.JButton();
        jButton_RotG = new javax.swing.JButton();
        jCheckBox_Oui = new javax.swing.JCheckBox();
        jSlider_Contraste = new javax.swing.JSlider();
        jPanel_InfoSalle = new javax.swing.JPanel();
        jLabel_Salle = new javax.swing.JLabel();
        jLabel_isNum = new javax.swing.JLabel();
        isNum = new javax.swing.JLabel();
        jLabel_Reference = new javax.swing.JLabel();
        jLabel_Reference1 = new javax.swing.JLabel();
        jLabel_Salle1 = new javax.swing.JLabel();
        jToggleButton_Sauvegarder1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Date : ");

        datelabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        datelabel.setText("Date");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rapport Acte");
        setFocusTraversalPolicyProvider(true);
        setResizable(false);

        JPanel_Base.setBackground(new java.awt.Color(204, 204, 255));
        JPanel_Base.setLayout(new java.awt.BorderLayout());

        Jpanel_Head.setBackground(new java.awt.Color(127, 144, 160));
        Jpanel_Head.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Image/medtechs_sansfond_petit.png"))); // NOI18N
        jLabel_Logo.setToolTipText("");

        jScrollPane1.setVisible(false);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane1.setViewportView(jTextArea2);
        jTextArea2.setVisible(false);

        javax.swing.GroupLayout Jpanel_HeadLayout = new javax.swing.GroupLayout(Jpanel_Head);
        Jpanel_Head.setLayout(Jpanel_HeadLayout);
        Jpanel_HeadLayout.setHorizontalGroup(
            Jpanel_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_HeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(572, Short.MAX_VALUE))
        );
        Jpanel_HeadLayout.setVerticalGroup(
            Jpanel_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_HeadLayout.createSequentialGroup()
                .addGroup(Jpanel_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel_HeadLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Jpanel_HeadLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        JPanel_Base.add(Jpanel_Head, java.awt.BorderLayout.NORTH);
        Jpanel_Head.getAccessibleContext().setAccessibleName("Head_Panel");

        jPanel_Corps.setBackground(new java.awt.Color(163, 209, 180));

        jPanel_InfoPatient.setBackground(new java.awt.Color(127, 144, 160));
        jPanel_InfoPatient.setBorder(javax.swing.BorderFactory.createTitledBorder("Information Patient"));

        jLabel_ID.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_ID.setText("Identifiant : ");

        jLabel_Nom.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_Nom.setText("Nom : ");

        jLabel_Prenom.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_Prenom.setText("Prénom : ");

        jLabel_DDN.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_DDN.setText("Date de naissance : ");

        jLabel_Sexe.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_Sexe.setText("Sexe : ");

        jLabel_Age.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_Age.setText("Age : ");

        jLabel_Adresse.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_Adresse.setText("Adresse :");

        idPatient.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        idPatient.setText(String.valueOf(patient_courant.getIdentifiant()));

        nomPatient.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        nomPatient.setText(patient_courant.getNom_d_usage());

        prenomPatient.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        prenomPatient.setText(patient_courant.getPrenom());

        dateNaissancePatient.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        dateNaissancePatient.setText(patient_courant.getDate_de_naissance().toString());

        sexePatient.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        sexePatient.setText(patient_courant.getGenre().toString());

        agePatient.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        agePatient.setText(String.valueOf(patient_courant.getAge()) + " ans");

        adressePatient.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        adressePatient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adressePatient.setText(patient_courant.getAdresse().toString());
        adressePatient.setToolTipText("");
        adressePatient.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel_InfoPatientLayout = new javax.swing.GroupLayout(jPanel_InfoPatient);
        jPanel_InfoPatient.setLayout(jPanel_InfoPatientLayout);
        jPanel_InfoPatientLayout.setHorizontalGroup(
            jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_InfoPatientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_InfoPatientLayout.createSequentialGroup()
                        .addGroup(jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Prenom)
                            .addComponent(jLabel_Nom)
                            .addComponent(jLabel_ID))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomPatient)
                            .addComponent(prenomPatient)
                            .addComponent(idPatient)))
                    .addGroup(jPanel_InfoPatientLayout.createSequentialGroup()
                        .addGroup(jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_DDN)
                            .addComponent(jLabel_Sexe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sexePatient)
                            .addComponent(dateNaissancePatient))))
                .addGap(25, 25, 25)
                .addGroup(jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_InfoPatientLayout.createSequentialGroup()
                        .addComponent(jLabel_Age)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(agePatient))
                    .addGroup(jPanel_InfoPatientLayout.createSequentialGroup()
                        .addComponent(jLabel_Adresse)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(adressePatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_InfoPatientLayout.setVerticalGroup(
            jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InfoPatientLayout.createSequentialGroup()
                .addGroup(jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ID)
                    .addComponent(idPatient)
                    .addComponent(jLabel_Age)
                    .addComponent(agePatient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Nom)
                    .addComponent(nomPatient)
                    .addComponent(jLabel_Adresse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_InfoPatientLayout.createSequentialGroup()
                        .addGroup(jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Prenom)
                            .addComponent(prenomPatient))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_DDN)
                            .addComponent(dateNaissancePatient))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Sexe)
                            .addComponent(sexePatient)))
                    .addComponent(adressePatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel_InfoActe.setBackground(new java.awt.Color(127, 144, 160));
        jPanel_InfoActe.setBorder(javax.swing.BorderFactory.createTitledBorder("Information Acte"));
        jPanel_InfoActe.setFocusCycleRoot(true);
        jPanel_InfoActe.setPreferredSize(new java.awt.Dimension(750, 500));

        jLabel_TypeExam.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_TypeExam.setText("Type Examen : ");

        jLabel_Nompract.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_Nompract.setText("Nom du Praticien : ");

        jLabel_Prenompract.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_Prenompract.setText("Prénom du Praticien : ");

        jLabel_IDpract.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_IDpract.setText("ID du Praticien : ");

        typeExamen.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        typeExamen.setText(examen_courant.getType_examen().toString());

        nomPraticien.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        nomPraticien.setText(examen_courant.getMedecin_en_charge().getNom());

        prenomPraticien.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        prenomPraticien.setText(examen_courant.getMedecin_en_charge().getPrenom());

        idPraticien.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        idPraticien.setText(String.valueOf(examen_courant.getMedecin_en_charge().getIdentifiant()));

        datexam.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        datexam.setText(examen_courant.getDate().toString());

        jLabel_LinkWord.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_LinkWord.setText("à");

        heurexam.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        heurexam.setText("00h00");

        jLabel_IDexam.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_IDexam.setText("ID examen : ");

        idexamen.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        idexamen.setText(String.valueOf(examen_courant.getId_examen()));

        jLabel_Indication.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_Indication.setText("Indication :");

        jTextPane_Indication.setEditable(false);
        jTextPane_Indication.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTextPane_Indication.setText(pacs_courant.getMention());
        jScrollPane_Indication.setViewportView(jTextPane_Indication);

        jLabel_Technique.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_Technique.setText("Technique");

        jTextPane_Technique.setEditable(false);
        jTextPane_Technique.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTextPane_Technique.setText(pacs_courant.getDescription());
        jScrollPane_Technique.setViewportView(jTextPane_Technique);

        javax.swing.GroupLayout jPanel_InfoActeLayout = new javax.swing.GroupLayout(jPanel_InfoActe);
        jPanel_InfoActe.setLayout(jPanel_InfoActeLayout);
        jPanel_InfoActeLayout.setHorizontalGroup(
            jPanel_InfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InfoActeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_InfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_Indication)
                    .addComponent(jScrollPane_Technique, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel_InfoActeLayout.createSequentialGroup()
                        .addGroup(jPanel_InfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Indication)
                            .addComponent(jLabel_Technique)
                            .addGroup(jPanel_InfoActeLayout.createSequentialGroup()
                                .addGroup(jPanel_InfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Prenompract)
                                    .addComponent(jLabel_IDpract)
                                    .addComponent(jLabel_Nompract)
                                    .addComponent(jLabel_TypeExam)
                                    .addGroup(jPanel_InfoActeLayout.createSequentialGroup()
                                        .addComponent(datexam)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel_LinkWord)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(heurexam)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_InfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_InfoActeLayout.createSequentialGroup()
                                        .addComponent(jLabel_IDexam)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(idexamen))
                                    .addComponent(typeExamen)
                                    .addComponent(nomPraticien)
                                    .addComponent(idPraticien)
                                    .addComponent(prenomPraticien))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator)
        );
        jPanel_InfoActeLayout.setVerticalGroup(
            jPanel_InfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InfoActeLayout.createSequentialGroup()
                .addGroup(jPanel_InfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TypeExam)
                    .addComponent(typeExamen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_InfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Nompract)
                    .addComponent(nomPraticien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_InfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Prenompract)
                    .addComponent(prenomPraticien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_InfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_IDpract)
                    .addComponent(idPraticien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_InfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datexam)
                    .addComponent(jLabel_LinkWord)
                    .addComponent(heurexam)
                    .addComponent(jLabel_IDexam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idexamen))
                .addGap(11, 11, 11)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Indication)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_Indication, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Technique)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_Technique, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel_Image.setBackground(new java.awt.Color(127, 144, 160));
        jPanel_Image.setBorder(javax.swing.BorderFactory.createTitledBorder("Apercu Cliché"));
        jPanel_Image.setPreferredSize(new java.awt.Dimension(350, 500));

        jComboBox_Image.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliché 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout imageRadioLayout = new javax.swing.GroupLayout(imageRadio);
        imageRadio.setLayout(imageRadioLayout);
        imageRadioLayout.setHorizontalGroup(
            imageRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );
        imageRadioLayout.setVerticalGroup(
            imageRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_ImageLayout = new javax.swing.GroupLayout(jPanel_Image);
        jPanel_Image.setLayout(jPanel_ImageLayout);
        jPanel_ImageLayout.setHorizontalGroup(
            jPanel_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ImageLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ImageLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(imageRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox_Image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel_ImageLayout.setVerticalGroup(
            jPanel_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ImageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox_Image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imageRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );

        jScrollPane_CR.setVisible(false);

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane_CR.setViewportView(jTextArea1);

        jLabel_AddRapport.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_AddRapport.setText("Ajouter rapport :");

        jButton_Sauvegarder.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton_Sauvegarder.setText("Sauvegarder");
        jButton_Sauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SauvegarderActionPerformed(evt);
            }
        });
        jButton_Sauvegarder.setVisible(false);

        jSlider_Luminosite.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jSlider_Luminosite.setOpaque(false);
        jSlider_Luminosite.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_LuminositeStateChanged(evt);
            }
        });

        jButton_RotD.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton_RotD.setText("D");
        jButton_RotD.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_RotD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RotDActionPerformed(evt);
            }
        });

        jLabel_Luminosite.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel_Luminosite.setText("Luminosité");

        jLabel_Contraste.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel_Contraste.setText("Contraste");

        jButton_Imprimer.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton_Imprimer.setText("Imprimer ");
        jButton_Imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ImprimerActionPerformed(evt);
            }
        });

        jButton_RotG.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton_RotG.setText("G");
        jButton_RotG.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_RotG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RotGActionPerformed(evt);
            }
        });

        jCheckBox_Oui.setText("Oui");
        jCheckBox_Oui.setOpaque(false);
        jCheckBox_Oui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_OuiActionPerformed(evt);
            }
        });

        jSlider_Contraste.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jSlider_Contraste.setOpaque(false);
        jSlider_Contraste.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_ContrasteStateChanged(evt);
            }
        });

        jPanel_InfoSalle.setBackground(new java.awt.Color(127, 144, 160));
        jPanel_InfoSalle.setBorder(javax.swing.BorderFactory.createTitledBorder("Information Salle"));
        jPanel_InfoSalle.setPreferredSize(new java.awt.Dimension(350, 500));

        jLabel_Salle.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_Salle.setText("Salle :");

        jLabel_isNum.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_isNum.setText("Numérique :");

        isNum.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        isNum.setText(salle_courante.isExamn_num());
        isNum.setToolTipText("");
        isNum.setToolTipText("");

        jLabel_Reference.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_Reference.setText("Référence dossier :");
        jLabel_Reference.setVisible(false);

        jLabel_Reference1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_Reference1.setText(String.valueOf(pacs_courant.getNumero_archive()));
        jLabel_Reference.setVisible(false);

        jLabel_Salle1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_Salle1.setText(String.valueOf(salle_courante.getNumero_salle()));

        javax.swing.GroupLayout jPanel_InfoSalleLayout = new javax.swing.GroupLayout(jPanel_InfoSalle);
        jPanel_InfoSalle.setLayout(jPanel_InfoSalleLayout);
        jPanel_InfoSalleLayout.setHorizontalGroup(
            jPanel_InfoSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InfoSalleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_InfoSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_InfoSalleLayout.createSequentialGroup()
                        .addComponent(jLabel_Reference)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Reference1))
                    .addGroup(jPanel_InfoSalleLayout.createSequentialGroup()
                        .addGroup(jPanel_InfoSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_isNum)
                            .addComponent(jLabel_Salle))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel_InfoSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isNum)
                            .addComponent(jLabel_Salle1))))
                .addGap(171, 171, 171))
        );
        jPanel_InfoSalleLayout.setVerticalGroup(
            jPanel_InfoSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InfoSalleLayout.createSequentialGroup()
                .addGroup(jPanel_InfoSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Salle)
                    .addComponent(jLabel_Salle1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_InfoSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_isNum)
                    .addComponent(isNum))
                .addGap(18, 18, 18)
                .addGroup(jPanel_InfoSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Reference)
                    .addComponent(jLabel_Reference1))
                .addGap(37, 37, 37))
        );

        if(isNum.getText().equals("Oui")){
            jLabel_Reference.setVisible(false);
        }
        else{
            jLabel_Reference.setVisible(true);
        }
        if(isNum.getText().equals("Oui")){
            jLabel_Reference1.setVisible(false);
        }
        else{
            jLabel_Reference1.setVisible(true);
        }

        jToggleButton_Sauvegarder1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jToggleButton_Sauvegarder1.setText("Inverser gris");
        jToggleButton_Sauvegarder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_Sauvegarder1ActionPerformed(evt);
            }
        });
        jButton_Sauvegarder.setVisible(false);

        jButton1.setText("Zoom");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_CorpsLayout = new javax.swing.GroupLayout(jPanel_Corps);
        jPanel_Corps.setLayout(jPanel_CorpsLayout);
        jPanel_CorpsLayout.setHorizontalGroup(
            jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CorpsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel_InfoActe, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                        .addComponent(jPanel_InfoPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane_CR))
                    .addGroup(jPanel_CorpsLayout.createSequentialGroup()
                        .addComponent(jLabel_AddRapport)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox_Oui)))
                .addGap(46, 46, 46)
                .addGroup(jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_CorpsLayout.createSequentialGroup()
                            .addComponent(jButton_Sauvegarder)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Imprimer))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CorpsLayout.createSequentialGroup()
                            .addGroup(jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel_CorpsLayout.createSequentialGroup()
                                    .addGap(0, 95, Short.MAX_VALUE)
                                    .addGroup(jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSlider_Luminosite, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSlider_Contraste, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(6, 6, 6))
                                .addGroup(jPanel_CorpsLayout.createSequentialGroup()
                                    .addGroup(jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jToggleButton_Sauvegarder1)
                                        .addComponent(jLabel_Contraste)
                                        .addComponent(jLabel_Luminosite))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel_CorpsLayout.createSequentialGroup()
                                    .addComponent(jButton_RotG, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addGap(25, 25, 25)
                                    .addComponent(jButton_RotD, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel_Image, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                        .addComponent(jPanel_InfoSalle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 420, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanel_CorpsLayout.setVerticalGroup(
            jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CorpsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_InfoPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_InfoSalle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_InfoActe, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_CorpsLayout.createSequentialGroup()
                        .addGroup(jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox_Oui)
                            .addComponent(jLabel_AddRapport)
                            .addComponent(jLabel_Luminosite))
                        .addGroup(jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_CorpsLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel_Contraste)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton_Sauvegarder1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CorpsLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane_CR, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel_CorpsLayout.createSequentialGroup()
                        .addGroup(jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton_RotG, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_RotD, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_CorpsLayout.createSequentialGroup()
                                .addComponent(jSlider_Luminosite, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(jSlider_Contraste, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Imprimer)
                            .addComponent(jButton_Sauvegarder))))
                .addGap(20, 20, 20))
        );

        JPanel_Base.add(jPanel_Corps, java.awt.BorderLayout.CENTER);

        getContentPane().add(JPanel_Base, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton_ImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Impression imprimer = new Impression(jTextArea1);
        imprimer.print();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {

        // TODO add your handling code here:
        String s = "";
        s += "Hôpital Princeton Plainsboro - Service de radiologie\n\n";
        s += "Rapport d'acte " + idexamen.getText() + " fait le " + datexam.getText() + " " + heurexam.getText() + "\n";
        s += "DR." + nomPraticien.getText() + " " + prenomPraticien.getText();
        s += "\n\n" + typeExamen.getText() + " Salle n°" + jLabel_Salle1.getText();
        s += "\nNumérique : " + isNum.getText();
        if (isNum.getText().equals("Non")) {
            s += "\nRéférence dossier papier : " + jLabel_Reference1.getText();
        }
        //s+="\n\n- Patient : \n";
        s += "\n\n---------------------------------------------------------------------------------------------------\n\n" + nomPatient.getText();
        s += " " + prenomPatient.getText();
        s += "\n\n- Indication : \n";
        s += jTextPane_Indication.getText();
        s += "\n\n- Technique : \n";
        s += jTextPane_Technique.getText();
        if (jCheckBox_Oui.isSelected()) {
            s += "\n\n- Rapport : \n" + jTextArea1.getText();
        }
        /*s+="\n\n- Actes medicaux : ";
         for (int i=0; i<actes.size(); i++) {
         Acte a = actes.get(i);
         s+="\n    > " + a.toString();
         }
         */
        jTextArea2.setText(s);

        Impression imprimer = new Impression(jTextArea2);
        imprimer.print();

    }

    private void jButton_SauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SauvegarderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_SauvegarderActionPerformed

    private void jCheckBox_OuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_OuiActionPerformed
        // TODO add your handling code here:
        if (jCheckBox_Oui.isSelected() == true) {
            jButton_Sauvegarder.setVisible(true);
            //jButton6.setVisible(true);
            jScrollPane_CR.setVisible(true);

            jPanel_Corps.repaint();
            jPanel_Corps.revalidate();

        } else if (jCheckBox_Oui.isSelected() == false) {
            jButton_Sauvegarder.setVisible(false);
            //jButton6.setVisible(false);
            jScrollPane_CR.setVisible(false);

            jPanel_Corps.repaint();
            jPanel_Corps.revalidate();

        }

    }//GEN-LAST:event_jCheckBox_OuiActionPerformed

    private void jButton_RotDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RotDActionPerformed
        // TODO add your handling code here:
        PanelImageRapport imageRadio_panel = (PanelImageRapport) imageRadio;
        imageRadio_panel.rotation_ImageD();
    }//GEN-LAST:event_jButton_RotDActionPerformed

    private void jSlider_ContrasteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_ContrasteStateChanged
        // TODO add your handling code here:
        PanelImageRapport imageRadio_panel = (PanelImageRapport) imageRadio;
        imageRadio_panel.setContraste(jSlider_Contraste.getValue());
       imageRadio_panel.augmenter_contraste();


    }//GEN-LAST:event_jSlider_ContrasteStateChanged

    private void jSlider_LuminositeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_LuminositeStateChanged
        // TODO add your handling code here:

        PanelImageRapport imageRadio_panel = (PanelImageRapport) imageRadio;
        imageRadio_panel.setLuminosité(jSlider_Luminosite.getValue());
        //PanelImageRapport.setLuminosité(jSlider_Luminosite.getValue());

         imageRadio_panel.augmenter_luminosite();
    }//GEN-LAST:event_jSlider_LuminositeStateChanged

    private void jButton_RotGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RotGActionPerformed
        // TODO add your handling code here:
                PanelImageRapport imageRadio_panel = (PanelImageRapport) imageRadio;
        imageRadio_panel.rotation_ImageG();
    }//GEN-LAST:event_jButton_RotGActionPerformed

    private void jToggleButton_Sauvegarder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_Sauvegarder1ActionPerformed
        // TODO add your handling code here:
        PanelImageRapport imageRadio_panel = (PanelImageRapport) imageRadio;
       imageRadio_panel.inverser_niveaux_de_gris();
    }//GEN-LAST:event_jToggleButton_Sauvegarder1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PanelImageRapport imageRadio_panel = (PanelImageRapport) imageRadio;
        imageRadio_panel.zoom();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crea_Rapport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crea_Rapport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crea_Rapport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crea_Rapport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crea_Rapport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel_Base;
    private javax.swing.JPanel Jpanel_Head;
    private javax.swing.JLabel adressePatient;
    private javax.swing.JLabel agePatient;
    private javax.swing.JLabel dateNaissancePatient;
    private javax.swing.JLabel datelabel;
    private javax.swing.JLabel datexam;
    private javax.swing.JLabel heurexam;
    private javax.swing.JLabel idPatient;
    private javax.swing.JLabel idPraticien;
    private javax.swing.JLabel idexamen;
    private javax.swing.JPanel imageRadio;
    private javax.swing.JLabel isNum;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Imprimer;
    private javax.swing.JButton jButton_RotD;
    private javax.swing.JButton jButton_RotG;
    private javax.swing.JButton jButton_Sauvegarder;
    private javax.swing.JButton jToggleButton_Sauvegarder1;
    private javax.swing.JCheckBox jCheckBox_Oui;
    private javax.swing.JComboBox<String> jComboBox_Image;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel_AddRapport;
    private javax.swing.JLabel jLabel_Adresse;
    private javax.swing.JLabel jLabel_Age;
    private javax.swing.JLabel jLabel_Contraste;
    private javax.swing.JLabel jLabel_DDN;
    private javax.swing.JLabel jLabel_ID;
    private javax.swing.JLabel jLabel_IDexam;
    private javax.swing.JLabel jLabel_IDpract;
    private javax.swing.JLabel jLabel_Indication;
    private javax.swing.JLabel jLabel_LinkWord;
    private javax.swing.JLabel jLabel_Logo;
    private javax.swing.JLabel jLabel_Luminosite;
    private javax.swing.JLabel jLabel_Nom;
    private javax.swing.JLabel jLabel_Nompract;
    private javax.swing.JLabel jLabel_Prenom;
    private javax.swing.JLabel jLabel_Prenompract;
    private javax.swing.JLabel jLabel_Reference;
    private javax.swing.JLabel jLabel_Reference1;
    private javax.swing.JLabel jLabel_Salle;
    private javax.swing.JLabel jLabel_Salle1;
    private javax.swing.JLabel jLabel_Sexe;
    private javax.swing.JLabel jLabel_Technique;
    private javax.swing.JLabel jLabel_TypeExam;
    private javax.swing.JLabel jLabel_isNum;
    private javax.swing.JPanel jPanel_Corps;
    private javax.swing.JPanel jPanel_Image;
    private javax.swing.JPanel jPanel_InfoActe;
    private javax.swing.JPanel jPanel_InfoPatient;
    private javax.swing.JPanel jPanel_InfoSalle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane_CR;
    private javax.swing.JScrollPane jScrollPane_Indication;
    private javax.swing.JScrollPane jScrollPane_Technique;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JSlider jSlider_Contraste;
    private javax.swing.JSlider jSlider_Luminosite;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextPane jTextPane_Indication;
    private javax.swing.JTextPane jTextPane_Technique;
    private javax.swing.JLabel nomPatient;
    private javax.swing.JLabel nomPraticien;
    private javax.swing.JLabel prenomPatient;
    private javax.swing.JLabel prenomPraticien;
    private javax.swing.JLabel sexePatient;
    private javax.swing.JLabel typeExamen;
    // End of variables declaration//GEN-END:variables
    private NF.PanelImageRapport PanelImageRapport;
}
