/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import BD.Gestion_examen;
import NF.DMR;
import NF.Examen;
import NF.Impression;
import NF.Medecin;
import NF.ObjetCourant;
import NF.PACS;
import NF.Patient;
import NF.Type_examen;

import java.awt.Image;
import java.sql.Connection;
import javax.swing.ImageIcon;

/**
 *
 * @author camin
 */
public class Modi_Acte extends javax.swing.JFrame {

    private Patient patient_courant;
    private Medecin medecin_courant;
    private DMR dmr_courant;
    private Examen examen_courant;
    private Connection connexion;

    public Modi_Acte() {
        initComponents();
    }

    /**
     * Creates new form Acceuille_Radiologue
     */
    public Modi_Acte(Patient patient_courant, Medecin medecin_courant, DMR dmr_courant, Examen examen_courant, ObjetCourant objet_Courant) {
        this.patient_courant = patient_courant;
        this.medecin_courant = medecin_courant;
        this.dmr_courant = dmr_courant;
        this.examen_courant = examen_courant;

        this.connexion = objet_Courant.getConnexion();

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        datelabel = new javax.swing.JLabel();
        JPanel_Base = new javax.swing.JPanel();
        Jpanel_Head = new javax.swing.JPanel();
        jLabel_Logo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel_Corps = new javax.swing.JPanel();
        jPanel_InfoPatient = new javax.swing.JPanel();
        jLabel_ID = new javax.swing.JLabel();
        jLabel_Nom = new javax.swing.JLabel();
        jLabel_Prenom = new javax.swing.JLabel();
        jLabel_DDN = new javax.swing.JLabel();
        jLabel_Sexe = new javax.swing.JLabel();
        jLabel_Age = new javax.swing.JLabel();
        jLabel_Adresse = new javax.swing.JLabel();
        idPatient = new javax.swing.JLabel();
        nomPatient = new javax.swing.JLabel();
        prenomPatient = new javax.swing.JLabel();
        dateNaissancePatient = new javax.swing.JLabel();
        sexePatient = new javax.swing.JLabel();
        agePatient = new javax.swing.JLabel();
        adressePatient = new javax.swing.JLabel();
        jPanel_InfoActe = new javax.swing.JPanel();
        jLabel_TypeExam = new javax.swing.JLabel();
        jLabel_Nompract = new javax.swing.JLabel();
        jLabel_Prenompract = new javax.swing.JLabel();
        jLabel_IDpract = new javax.swing.JLabel();
        typeExamen = new javax.swing.JLabel();
        nomPraticien = new javax.swing.JLabel();
        prenomPraticien = new javax.swing.JLabel();
        idPraticien = new javax.swing.JLabel();
        datexam = new javax.swing.JLabel();
        jLabel_LinkWord = new javax.swing.JLabel();
        heurexam = new javax.swing.JLabel();
        jLabel_IDexam = new javax.swing.JLabel();
        idexamen = new javax.swing.JLabel();
        jSeparator = new javax.swing.JSeparator();
        jLabel_Indication = new javax.swing.JLabel();
        jScrollPane_Indication = new javax.swing.JScrollPane();
        jTextPane_Indication = new javax.swing.JTextPane();
        jPanel_InfoSalle = new javax.swing.JPanel();
        jLabel_Salle = new javax.swing.JLabel();
        jLabel_isNum = new javax.swing.JLabel();
        isNum = new javax.swing.JLabel();
        jLabel_Reference = new javax.swing.JLabel();
        jTextField_Refenrece = new javax.swing.JTextField();
        jComboBox_Salle = new javax.swing.JComboBox<String>();
        jScrollPane_Technique = new javax.swing.JScrollPane();
        jTextArea_Technique = new javax.swing.JTextArea();
        jLabel_Technique = new javax.swing.JLabel();
        jButton_Sauvegarder = new javax.swing.JButton();
        jButton_SauvegarderFermer = new javax.swing.JButton();
        jButton_Imprimer = new javax.swing.JButton();
        jLabel_Com = new javax.swing.JLabel();
        jScrollPane_Com = new javax.swing.JScrollPane();
        jTextArea_Com = new javax.swing.JTextArea();

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Date : ");

        datelabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        datelabel.setText("Date");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rapport Acte");
        setFocusTraversalPolicyProvider(true);
        setResizable(false);

        JPanel_Base.setBackground(new java.awt.Color(204, 204, 255));
        JPanel_Base.setLayout(new java.awt.BorderLayout());

        Jpanel_Head.setBackground(new java.awt.Color(127, 144, 160));
        Jpanel_Head.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Image/medtechs_sansfond_petit.png"))); // NOI18N
        jLabel_Logo.setToolTipText("");

        jScrollPane1.setVisible(false);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane1.setViewportView(jTextArea2);

        javax.swing.GroupLayout Jpanel_HeadLayout = new javax.swing.GroupLayout(Jpanel_Head);
        Jpanel_Head.setLayout(Jpanel_HeadLayout);
        Jpanel_HeadLayout.setHorizontalGroup(
            Jpanel_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_HeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 372, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287))
        );
        Jpanel_HeadLayout.setVerticalGroup(
            Jpanel_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_HeadLayout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(Jpanel_HeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPanel_Base.add(Jpanel_Head, java.awt.BorderLayout.NORTH);
        Jpanel_Head.getAccessibleContext().setAccessibleName("Head_Panel");

        jPanel_Corps.setBackground(new java.awt.Color(163, 209, 180));

        jPanel_InfoPatient.setBackground(new java.awt.Color(127, 144, 160));
        jPanel_InfoPatient.setBorder(javax.swing.BorderFactory.createTitledBorder("Information Patient"));

        jLabel_ID.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_ID.setText("Identifiant : ");

        jLabel_Nom.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_Nom.setText("Nom : ");

        jLabel_Prenom.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_Prenom.setText("Prénom : ");

        jLabel_DDN.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_DDN.setText("Date de naissance : ");

        jLabel_Sexe.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_Sexe.setText("Sexe : ");

        jLabel_Age.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_Age.setText("Age : ");

        jLabel_Adresse.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_Adresse.setText("Adresse :");

        idPatient.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        idPatient.setText(String.valueOf(patient_courant.getIdentifiant()));

        nomPatient.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        nomPatient.setText(patient_courant.getNom_d_usage());

        prenomPatient.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        prenomPatient.setText(patient_courant.getPrenom());

        dateNaissancePatient.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        dateNaissancePatient.setText(patient_courant.getDate_de_naissance().toString());

        sexePatient.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        sexePatient.setText(patient_courant.getGenre().toString());

        agePatient.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        agePatient.setText(String.valueOf(patient_courant.getAge()));

        adressePatient.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        adressePatient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adressePatient.setText(patient_courant.getAdresse().toString());
        adressePatient.setToolTipText("");
        adressePatient.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel_InfoPatientLayout = new javax.swing.GroupLayout(jPanel_InfoPatient);
        jPanel_InfoPatient.setLayout(jPanel_InfoPatientLayout);
        jPanel_InfoPatientLayout.setHorizontalGroup(
            jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_InfoPatientLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_InfoPatientLayout.createSequentialGroup()
                        .addGroup(jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Prenom)
                            .addComponent(jLabel_Nom)
                            .addComponent(jLabel_ID))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomPatient)
                            .addComponent(prenomPatient)
                            .addComponent(idPatient)))
                    .addGroup(jPanel_InfoPatientLayout.createSequentialGroup()
                        .addGroup(jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_DDN)
                            .addComponent(jLabel_Sexe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sexePatient)
                            .addComponent(dateNaissancePatient))))
                .addGap(25, 25, 25)
                .addGroup(jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_InfoPatientLayout.createSequentialGroup()
                        .addComponent(jLabel_Age)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(agePatient))
                    .addGroup(jPanel_InfoPatientLayout.createSequentialGroup()
                        .addGroup(jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Adresse)
                            .addComponent(adressePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_InfoPatientLayout.setVerticalGroup(
            jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InfoPatientLayout.createSequentialGroup()
                .addGroup(jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ID)
                    .addComponent(idPatient)
                    .addComponent(jLabel_Age)
                    .addComponent(agePatient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Nom)
                    .addComponent(nomPatient)
                    .addComponent(jLabel_Adresse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adressePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_InfoPatientLayout.createSequentialGroup()
                        .addGroup(jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Prenom)
                            .addComponent(prenomPatient))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_DDN)
                            .addComponent(dateNaissancePatient))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_InfoPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Sexe)
                            .addComponent(sexePatient)))))
        );

        jPanel_InfoActe.setBackground(new java.awt.Color(127, 144, 160));
        jPanel_InfoActe.setBorder(javax.swing.BorderFactory.createTitledBorder("Information Acte"));
        jPanel_InfoActe.setFocusCycleRoot(true);
        jPanel_InfoActe.setPreferredSize(new java.awt.Dimension(750, 500));

        jLabel_TypeExam.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_TypeExam.setText("Type Examen : ");

        jLabel_Nompract.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_Nompract.setText("Nom du Praticien : ");

        jLabel_Prenompract.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_Prenompract.setText("Prénom du Praticien : ");

        jLabel_IDpract.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_IDpract.setText("ID du Praticien : ");

        typeExamen.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        typeExamen.setText(examen_courant.getType());

        nomPraticien.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        nomPraticien.setText(medecin_courant.getNom());

        prenomPraticien.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        prenomPraticien.setText(medecin_courant.getPrenom());

        idPraticien.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        idPraticien.setText(String.valueOf(medecin_courant.getIdentifiant()));

        datexam.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        datexam.setText(examen_courant.getDate().toString());

        jLabel_LinkWord.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_LinkWord.setText("à");

        heurexam.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        heurexam.setText("00h00");

        jLabel_IDexam.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_IDexam.setText("ID examen : ");

        idexamen.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        idexamen.setText(String.valueOf(examen_courant.getId_examen()));

        jLabel_Indication.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_Indication.setText("Indication :");

        jTextPane_Indication.setEditable(true);
        jTextPane_Indication.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jScrollPane_Indication.setViewportView(jTextPane_Indication);

        javax.swing.GroupLayout jPanel_InfoActeLayout = new javax.swing.GroupLayout(jPanel_InfoActe);
        jPanel_InfoActe.setLayout(jPanel_InfoActeLayout);
        jPanel_InfoActeLayout.setHorizontalGroup(
            jPanel_InfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InfoActeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_InfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_Indication)
                    .addGroup(jPanel_InfoActeLayout.createSequentialGroup()
                        .addGroup(jPanel_InfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Indication)
                            .addGroup(jPanel_InfoActeLayout.createSequentialGroup()
                                .addComponent(jLabel_TypeExam)
                                .addGap(57, 57, 57)
                                .addComponent(typeExamen))
                            .addGroup(jPanel_InfoActeLayout.createSequentialGroup()
                                .addComponent(jLabel_Nompract)
                                .addGap(32, 32, 32)
                                .addComponent(nomPraticien))
                            .addGroup(jPanel_InfoActeLayout.createSequentialGroup()
                                .addGroup(jPanel_InfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Prenompract)
                                    .addComponent(jLabel_IDpract))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_InfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idPraticien)
                                    .addComponent(prenomPraticien)))
                            .addGroup(jPanel_InfoActeLayout.createSequentialGroup()
                                .addComponent(datexam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_LinkWord)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(heurexam)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_IDexam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idexamen)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator)
        );
        jPanel_InfoActeLayout.setVerticalGroup(
            jPanel_InfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InfoActeLayout.createSequentialGroup()
                .addGroup(jPanel_InfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TypeExam)
                    .addComponent(typeExamen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_InfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Nompract)
                    .addComponent(nomPraticien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_InfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Prenompract)
                    .addComponent(prenomPraticien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_InfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_IDpract)
                    .addComponent(idPraticien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_InfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datexam)
                    .addComponent(jLabel_LinkWord)
                    .addComponent(heurexam)
                    .addComponent(jLabel_IDexam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idexamen))
                .addGap(11, 11, 11)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Indication)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_Indication, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel_InfoSalle.setBackground(new java.awt.Color(127, 144, 160));
        jPanel_InfoSalle.setBorder(javax.swing.BorderFactory.createTitledBorder("Information Salle"));
        jPanel_InfoSalle.setPreferredSize(new java.awt.Dimension(350, 500));

        jLabel_Salle.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_Salle.setText("Salle :");

        jLabel_isNum.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_isNum.setText("Numérique :");

        isNum.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        if (examen_courant.isDossier_papier()){
            isNum.setText("Non");
        }
        else{
            isNum.setText("Oui");
        }
        isNum.setToolTipText("");

        jLabel_Reference.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel_Reference.setText("Référence dossier :");
        jLabel_Reference.setVisible(false);

        jTextField_Refenrece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_RefenreceActionPerformed(evt);
            }
        });
        jTextField_Refenrece.setVisible(false);

        jComboBox_Salle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        jComboBox_Salle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_SalleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_InfoSalleLayout = new javax.swing.GroupLayout(jPanel_InfoSalle);
        jPanel_InfoSalle.setLayout(jPanel_InfoSalleLayout);
        jPanel_InfoSalleLayout.setHorizontalGroup(
            jPanel_InfoSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InfoSalleLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel_InfoSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_InfoSalleLayout.createSequentialGroup()
                        .addComponent(jLabel_Reference)
                        .addGap(24, 24, 24)
                        .addComponent(jTextField_Refenrece, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_InfoSalleLayout.createSequentialGroup()
                        .addGroup(jPanel_InfoSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_isNum)
                            .addGroup(jPanel_InfoSalleLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel_Salle)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_InfoSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isNum)
                            .addComponent(jComboBox_Salle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel_InfoSalleLayout.setVerticalGroup(
            jPanel_InfoSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InfoSalleLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel_InfoSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Salle)
                    .addComponent(jComboBox_Salle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel_InfoSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_isNum)
                    .addComponent(isNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_InfoSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Reference)
                    .addComponent(jTextField_Refenrece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextArea_Technique.setColumns(20);
        jTextArea_Technique.setLineWrap(true);
        jTextArea_Technique.setRows(5);
        jTextArea_Technique.setLineWrap(true);
        jScrollPane_Technique.setViewportView(jTextArea_Technique);

        jLabel_Technique.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Technique.setText("Technique imagerie :");

        jButton_Sauvegarder.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton_Sauvegarder.setText("Sauvegarder");
        jButton_Sauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SauvegarderActionPerformed(evt);
            }
        });

        jButton_SauvegarderFermer.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton_SauvegarderFermer.setText("Sauvegarde et fermer");
        jButton_SauvegarderFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SauvegarderFermerActionPerformed(evt);
            }
        });

        jButton_Imprimer.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton_Imprimer.setText("Imprimer ");
        jButton_Imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ImprimerActionPerformed(evt);
            }
        });

        jLabel_Com.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Com.setText("Commentaire :");

        jTextArea_Com.setColumns(20);
        jTextArea_Com.setLineWrap(true);
        jTextArea_Com.setRows(5);
        jTextArea_Com.setLineWrap(true);
        jScrollPane_Com.setViewportView(jTextArea_Com);

        javax.swing.GroupLayout jPanel_CorpsLayout = new javax.swing.GroupLayout(jPanel_Corps);
        jPanel_Corps.setLayout(jPanel_CorpsLayout);
        jPanel_CorpsLayout.setHorizontalGroup(
            jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CorpsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane_Technique)
                    .addGroup(jPanel_CorpsLayout.createSequentialGroup()
                        .addGroup(jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Technique)
                            .addComponent(jPanel_InfoActe, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                            .addComponent(jButton_Imprimer)
                            .addComponent(jPanel_InfoPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_CorpsLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane_Com, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Com, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel_InfoSalle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CorpsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Sauvegarder)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_SauvegarderFermer)))))
                .addGap(20, 20, 20))
        );
        jPanel_CorpsLayout.setVerticalGroup(
            jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CorpsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_InfoSalle, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jPanel_InfoPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_CorpsLayout.createSequentialGroup()
                        .addGroup(jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel_InfoActe, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CorpsLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane_Com, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addComponent(jLabel_Technique))
                    .addComponent(jLabel_Com))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane_Technique, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Imprimer)
                    .addComponent(jButton_SauvegarderFermer)
                    .addComponent(jButton_Sauvegarder))
                .addGap(22, 22, 22))
        );

        JPanel_Base.add(jPanel_Corps, java.awt.BorderLayout.CENTER);

        getContentPane().add(JPanel_Base, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Impression imprimer = new Impression(jTextArea1);
        //imprimer.print();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton_ImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ImprimerActionPerformed
        // TODO add your handling code here:
        String s = "";
        s += "Hôpital Princeton Plainsboro - Service de radiologie\n\n";
        s += "Rapport d'acte " + idexamen.getText() + " fait le " + datexam.getText() + " " + heurexam.getText() + "\n";
        s += "DR." + nomPraticien.getText() + " " + prenomPraticien.getText();
        s += "\n\n" + typeExamen.getText() + " Salle n°" + jComboBox_Salle.getSelectedItem();
        s += "\nNumérique : " + isNum.getText();
        if (isNum.getText().equals("Non")) {
            s += "\nRéférence dossier papier : " + jTextField_Refenrece.getText();
        }
        //s+="\n\n- Patient : \n";
        s += "\n\n---------------------------------------------------------------------------------------------------\n\n" + nomPatient.getText();
        s += " " + prenomPatient.getText();
        s += "\n\n- Indication : \n";
        s += jTextPane_Indication.getText();
        s += "\n\n- Technique : \n";
        s += jTextArea_Technique.getText();
        jTextArea2.setText(s);
        Impression imprimer = new Impression(jTextArea2);
        imprimer.print();

    }//GEN-LAST:event_jButton_ImprimerActionPerformed

    private void jButton_SauvegarderFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SauvegarderFermerActionPerformed
        // TODO add your handling code here:
        examen_courant.setCR(jTextArea_Com.getText());
        examen_courant.setDate(examen_courant.getDate());
        examen_courant.setId_dmr(this.dmr_courant.getId_dmr());
        if (examen_courant.isDossier_papier()) {
            examen_courant.setDoss_papier(1);
        } else {
            examen_courant.setDoss_papier(0);
        }

        examen_courant.setDuree_prevue(examen_courant.getDuree_prevue());
        examen_courant.setId_historique(examen_courant.getHistorique_modifications().getId_historique());
        examen_courant.setIdSalle(jComboBox_Salle.getSelectedIndex());
        examen_courant.setPacs(Integer.parseInt(jTextField_Refenrece.getText()));
        examen_courant.setId_medecin(medecin_courant.getIdentifiant());
        examen_courant.setType(examen_courant.getType());

        Gestion_examen.creerExamen(examen_courant, this.connexion);
        PACS pacs = new PACS(Integer.parseInt(jTextField_Refenrece.getText()), jTextPane_Indication.getText(), jTextArea_Technique.getText());
        Gestion_examen.creerPacs(pacs, this.connexion);

        //fermer la fenetre
    }//GEN-LAST:event_jButton_SauvegarderFermerActionPerformed

    private void jButton_SauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SauvegarderActionPerformed
        // TODO add your handling code here:
        PACS pacs = null;
        examen_courant.setCR(jTextArea_Com.getText());
        examen_courant.setDate(examen_courant.getDate());
        examen_courant.setId_dmr(this.dmr_courant.getId_dmr());
        if (examen_courant.isDossier_papier()) {
            examen_courant.setDoss_papier(1);
            examen_courant.setPacs(Integer.parseInt(jTextField_Refenrece.getText()));
            pacs = new PACS(Integer.parseInt(jTextField_Refenrece.getText()), jTextPane_Indication.getText(), jTextArea_Technique.getText());
        } else {
            examen_courant.setDoss_papier(0);
            //modifier le numero du pacs!!!!
            examen_courant.setPacs(16);
            pacs = new PACS(16, jTextPane_Indication.getText(), jTextArea_Technique.getText());
        }

        examen_courant.setDuree_prevue(examen_courant.getDuree_prevue());
        //examen_courant.setId_historique(examen_courant.getHistorique_modifications().getId_historique());
        //modifier le numero de l'historique!!!!
        examen_courant.setId_historique(1);

        examen_courant.setIdSalle((jComboBox_Salle.getSelectedIndex() + 1));
        System.out.println((jComboBox_Salle.getSelectedIndex() + 1));

        examen_courant.setId_medecin(medecin_courant.getIdentifiant());
        examen_courant.setType(examen_courant.getType());

        Gestion_examen.creerExamen(examen_courant, this.connexion);

        Gestion_examen.creerPacs(pacs, this.connexion);

    }//GEN-LAST:event_jButton_SauvegarderActionPerformed

    private void jTextField_RefenreceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_RefenreceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_RefenreceActionPerformed

    private void jComboBox_SalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_SalleActionPerformed
        // TODO add your handling code here:
        if (jComboBox_Salle.getSelectedItem().equals("1") | jComboBox_Salle.getSelectedItem().equals("2") | jComboBox_Salle.getSelectedItem().equals("3") | jComboBox_Salle.getSelectedItem().equals("4") | jComboBox_Salle.getSelectedItem().equals("5") | jComboBox_Salle.getSelectedItem().equals("6")) {
            isNum.setText("Oui");
        } else {
            isNum.setText("Non");
        }
        if (isNum.getText().equals("Non")) {
            jTextField_Refenrece.setVisible(true);
            jLabel_Reference.setVisible(true);

            jPanel_InfoSalle.repaint();
            jPanel_InfoSalle.revalidate();

        } else if (isNum.getText().equals("Oui")) {
            jTextField_Refenrece.setVisible(false);
            jLabel_Reference.setVisible(false);

            jPanel_InfoSalle.repaint();
            jPanel_InfoSalle.revalidate();

        }
    }//GEN-LAST:event_jComboBox_SalleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crea_Acte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crea_Acte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crea_Acte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crea_Acte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crea_Acte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel_Base;
    private javax.swing.JPanel Jpanel_Head;
    private javax.swing.JLabel adressePatient;
    private javax.swing.JLabel agePatient;
    private javax.swing.JLabel dateNaissancePatient;
    private javax.swing.JLabel datelabel;
    private javax.swing.JLabel datexam;
    private javax.swing.JLabel heurexam;
    private javax.swing.JLabel idPatient;
    private javax.swing.JLabel idPraticien;
    private javax.swing.JLabel idexamen;
    private javax.swing.JLabel isNum;
    private javax.swing.JButton jButton_Imprimer;
    private javax.swing.JButton jButton_Sauvegarder;
    private javax.swing.JButton jButton_SauvegarderFermer;
    private javax.swing.JComboBox<String> jComboBox_Salle;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel_Adresse;
    private javax.swing.JLabel jLabel_Age;
    private javax.swing.JLabel jLabel_Com;
    private javax.swing.JLabel jLabel_DDN;
    private javax.swing.JLabel jLabel_ID;
    private javax.swing.JLabel jLabel_IDexam;
    private javax.swing.JLabel jLabel_IDpract;
    private javax.swing.JLabel jLabel_Indication;
    private javax.swing.JLabel jLabel_LinkWord;
    private javax.swing.JLabel jLabel_Logo;
    private javax.swing.JLabel jLabel_Nom;
    private javax.swing.JLabel jLabel_Nompract;
    private javax.swing.JLabel jLabel_Prenom;
    private javax.swing.JLabel jLabel_Prenompract;
    private javax.swing.JLabel jLabel_Reference;
    private javax.swing.JLabel jLabel_Salle;
    private javax.swing.JLabel jLabel_Sexe;
    private javax.swing.JLabel jLabel_Technique;
    private javax.swing.JLabel jLabel_TypeExam;
    private javax.swing.JLabel jLabel_isNum;
    private javax.swing.JPanel jPanel_Corps;
    private javax.swing.JPanel jPanel_InfoActe;
    private javax.swing.JPanel jPanel_InfoPatient;
    private javax.swing.JPanel jPanel_InfoSalle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane_Com;
    private javax.swing.JScrollPane jScrollPane_Indication;
    private javax.swing.JScrollPane jScrollPane_Technique;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea_Com;
    private javax.swing.JTextArea jTextArea_Technique;
    private javax.swing.JTextField jTextField_Refenrece;
    private javax.swing.JTextPane jTextPane_Indication;
    private javax.swing.JLabel nomPatient;
    private javax.swing.JLabel nomPraticien;
    private javax.swing.JLabel prenomPatient;
    private javax.swing.JLabel prenomPraticien;
    private javax.swing.JLabel sexePatient;
    private javax.swing.JLabel typeExamen;
    // End of variables declaration//GEN-END:variables
}
