package UI_Anglais;

import NF.ObjetCourant;

import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class ChangerMdp_Sec extends JFrame{
    private Connection connexion;
    private ObjetCourant objet_Courant;

    /**
     * Creates new form ChangerMdp_Radiologue
     */
    public ChangerMdp_Sec(ObjetCourant objet_Courant) {
        this.objet_Courant = objet_Courant;
        connexion = objet_Courant.getConnexion();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        login = new JButton();
        jPanelPrincipal = new JPanel();
        jPanelSecondaire = new JPanel();
        jLabelTitre = new JLabel();
        jLabelMdpActuel = new JLabel();
        jLabelnewMdp = new JLabel();
        jLabelId = new JLabel();
        jLabelconfirmer = new JLabel();
        jTextFieldId = new JTextField();
        jPasswordFieldmdpActuel = new JPasswordField();
        jCheckBoxActuel = new JCheckBox();
        jPasswordFieldnouveau = new JPasswordField();
        jPasswordFieldConfirmer = new JPasswordField();
        jCheckBoxNew1 = new JCheckBox();
        jButtonValider = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jPanelPrincipal.setBackground(new java.awt.Color(163, 209, 180));

        jPanelSecondaire.setBackground(new java.awt.Color(127, 144, 160));

        jLabelTitre.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabelTitre.setText("Changement de mot de passe");

        GroupLayout jPanelSecondaireLayout = new GroupLayout(jPanelSecondaire);
        jPanelSecondaire.setLayout(jPanelSecondaireLayout);
        jPanelSecondaireLayout.setHorizontalGroup(
                jPanelSecondaireLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelSecondaireLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabelTitre)
                                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanelSecondaireLayout.setVerticalGroup(
                jPanelSecondaireLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelSecondaireLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabelTitre)
                                .addContainerGap(64, Short.MAX_VALUE))
        );

        jLabelMdpActuel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMdpActuel.setText("Ancient mot de passe :");

        jLabelnewMdp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelnewMdp.setText("Nouveau mot de passe :");

        jLabelId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelId.setText("Identifiant :");

        jLabelconfirmer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelconfirmer.setText("Confirmer mot de passe :");

        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });

        jCheckBoxActuel.setBackground(new java.awt.Color(163, 209, 180));
        jCheckBoxActuel.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jCheckBoxActuel.setText("Afficher Mot de Passe");
        jCheckBoxActuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxActuelActionPerformed(evt);
            }
        });

        jPasswordFieldConfirmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldConfirmerActionPerformed(evt);
            }
        });

        jCheckBoxNew1.setBackground(new java.awt.Color(163, 209, 180));
        jCheckBoxNew1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jCheckBoxNew1.setText("Afficher Mot de Passe");
        jCheckBoxNew1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxNew1ActionPerformed(evt);
            }
        });

        jButtonValider.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonValider.setForeground(new java.awt.Color(72, 91, 122));
        jButtonValider.setText("Valider");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });

        GroupLayout jPanelPrincipalLayout = new GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
                jPanelPrincipalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelSecondaire, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelPrincipalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addGroup(GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                                                        .addComponent(jLabelId)
                                                        .addGap(143, 143, 143))
                                                .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                                        .addComponent(jLabelMdpActuel)
                                                        .addGap(48, 48, 48)))
                                        .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                                .addComponent(jLabelnewMdp)
                                                .addGap(36, 36, 36))
                                        .addComponent(jLabelconfirmer))
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                                .addGroup(jPanelPrincipalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                                                .addComponent(jPasswordFieldnouveau, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jCheckBoxNew1))
                                                        .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                                                .addComponent(jPasswordFieldmdpActuel, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jCheckBoxActuel))
                                                        .addComponent(jTextFieldId, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                                .addComponent(jPasswordFieldConfirmer, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonValider, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                                                .addGap(61, 61, 61))))
        );
        jPanelPrincipalLayout.setVerticalGroup(
                jPanelPrincipalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addComponent(jPanelSecondaire, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addComponent(jLabelId))
                                        .addGroup(GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addComponent(jTextFieldId, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)))
                                .addGap(45, 45, 45)
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelMdpActuel)
                                        .addComponent(jPasswordFieldmdpActuel, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCheckBoxActuel))
                                .addGap(45, 45, 45)
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelnewMdp)
                                        .addComponent(jPasswordFieldnouveau, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCheckBoxNew1))
                                .addGap(45, 45, 45)
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelconfirmer)
                                        .addComponent(jPasswordFieldConfirmer, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonValider, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 45, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelPrincipal, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelPrincipal, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jCheckBoxActuelActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (jCheckBoxActuel.isSelected()) {
            jPasswordFieldmdpActuel.setEchoChar((char) 0);
        } else {
            jPasswordFieldmdpActuel.setEchoChar('*');
        }

    }

    private void jPasswordFieldConfirmerActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jCheckBoxNew1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        if (jCheckBoxNew1.isSelected()) {
            jPasswordFieldnouveau.setEchoChar((char) 0);
        } else {
            jPasswordFieldnouveau.setEchoChar('*');
        }
    }

    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        boolean verif = false;

        try {

            PreparedStatement statement;
            statement = connexion.prepareStatement("SELECT * FROM connexion");
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                String loginUtilisateur = rs.getString("id_user");
                String loginChanger = jTextFieldId.getText();
                char[] ancienMdp = jPasswordFieldmdpActuel.getPassword();
                String motPasseUtilisateur = rs.getString("mdp");
                String mdpActuel = String.valueOf(ancienMdp);
                if (loginUtilisateur.equals(loginChanger) && motPasseUtilisateur.equals(mdpActuel)) {
                    verif = true;

                    PreparedStatement stat;
                    stat = connexion.prepareStatement("UPDATE connexion SET mdp ="
                            + String.valueOf(jPasswordFieldnouveau.getPassword())
                            + " WHERE id_user = " + jTextFieldId.getText() + "");
                    if (String.valueOf(jPasswordFieldnouveau.getPassword()).equals(String.valueOf(jPasswordFieldConfirmer.getPassword()))) {
                        stat.executeUpdate();
                    }


                    Acceuil_Sec retourAccueil_Sec = new Acceuil_Sec(objet_Courant);
                    retourAccueil_Sec.setVisible(true);
                    this.dispose();

                }
            }
            if (verif == false) {
                JOptionPane.showMessageDialog(null, "Verifier le login ou le Mot de passe", "Message d'erreur:", JOptionPane.ERROR_MESSAGE);
                jTextFieldId.setText("");
                jPasswordFieldmdpActuel.setText("");
            }
        } //catch (SQLException ex) {
        //   Logger.getLogger(ChangerMotPasseJFrame.class.getName()).log(Level.SEVERE, null, ex);
        //}
        catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangerMdp_Radiologue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangerMdp_Radiologue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangerMdp_Radiologue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangerMdp_Radiologue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify
    private JButton jButtonValider;
    private JCheckBox jCheckBoxActuel;
    private JCheckBox jCheckBoxNew1;
    private JLabel jLabelId;
    private JLabel jLabelMdpActuel;
    private JLabel jLabelTitre;
    private JLabel jLabelconfirmer;
    private JLabel jLabelnewMdp;
    private JPanel jPanelPrincipal;
    private JPanel jPanelSecondaire;
    private JPasswordField jPasswordFieldConfirmer;
    private JPasswordField jPasswordFieldmdpActuel;
    private JPasswordField jPasswordFieldnouveau;
    private JTextField jTextFieldId;
    private JButton login;
    // End of variables declaration

}
